### ISSUE TITLE
Not listed yet: bitergia.com

### ISSUE THREAD

**Issue by GeorgLink** [SociallyCompute/Global-Consent-Manager#103]
The website at this url is unlisted: https://bitergia.com/

**Comment by dmarti** [comment]
Is the cookie popup on this site a GDPR dialog?

 * I'm not asked for consent and the dialog goes away after waiting.

 * Clicking the button just seems to set a "cookiesDirective" cookie to 1, not recording consent to anything.

Is this site just doing legitimate interest (LI) tracking and is not actually trying to get consent?

**Comment by GeorgLink** [comment]
Bitergia is redesigning the website anyway right now. Whatever the solution is, it will probably change in a matter of weeks.
