### ISSUE TITLE
Not listed yet: www.ft.com

### ISSUE THREAD

**Issue by mozfreddyb** [SociallyCompute/Global-Consent-Manager#110]
The website at this url is unlisted: https://www.ft.com/content/663087c2-77c1-11e9-bbad-7c18c0ea0201

**Comment by dmarti** [comment]
This is an interesting one.

Looks like they need to have this cookie set in order to clear out the permissions but they check another cookie to see if they need to display the dialog.

```
    {
        domain: "ft.com",
        name: "FTConsent",
        value: "marketingBypost%3Aoff%2CmarketingByemail%3Aoff%2CmarketingByphonecall%3Aoff%2CmarketingByfax%3Aoff%2CmarketingBysms%3Aoff%2CenhancementBypost%3Aoff%2CenhancementByemail%3Aoff%2CenhancementByphonecall%3Aoff%2CenhancementByfax%3Aoff%2CenhancementBysms%3Aoff%2CbehaviouraladsOnsite%3Aoff%2CdemographicadsOnsite%3Aoff%2CrecommendedcontentOnsite%3Aoff%2CprogrammaticadsOnsite%3Aoff%2CcookiesUseraccept%3Aoff%2CcookiesOnsite%3Aoff%2CmembergetmemberByemail%3Aoff",
}
```

Can we set more than 1 cookie in the config for the same site?  cc @zombie

**Comment by dmarti** [comment]
To set multiple cookies for the same site you can make multiple records in sites.js
