### ISSUE TITLE
Import IAB list

### ISSUE THREAD

**Issue by dmarti** [SociallyCompute/Global-Consent-Manager#118]
We need to do updates from the IAB site (details?)

@zombie

**Comment by dmarti** [comment]
Not needed for Experiment. We just have to have a no consent for anyone cookie value

cc @zombie -- please close when you are satisfied with this.

**Comment by zombie** [comment]
I downloaded the list locally, generated the cookie and added it [here](https://github.com/SociallyCompute/Global-Consent-Manager/commit/475b09e8a5ab461e83757ccf6c2722ba0876e219), we don't need to do this at runtime.
