### ISSUE TITLE
TCF 1.0 general support

### ISSUE THREAD

**Issue by dmarti** [SociallyCompute/Global-Consent-Manager#120]
(remove special cased sites from config)

**Comment by dmarti** [comment]
Mainly focusing on vendors, no standard way to locate the publisher's consent cookie.

https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md

**Comment by dmarti** [comment]
Sounds like we need to do 2 things.

1. Populate "euconsent" with No Consent values. This will get the 3rd parties -- so any 3rd party that is checking for consent won't get it.

2. Hide the consent dialog if needed. (possibly use the "I don't care about cookies" method)

**Comment by dmarti** [comment]
We will NOT be able to do "eupubconsent" cookie because this is insufficiently standardized. (And we're not concerned about publisher 1st-party data anyway.)

**Comment by dmarti** [comment]
@zombie let's make this the 1st feature one.

**Comment by zombie** [comment]
TCF is mainly concerned with 3rd party vendors, not first party publishers, and thus adding general support for it it would do little to nothing for the user experience at this point.  For now, we are only setting the [global "no consent" cookie](https://github.com/SociallyCompute/Global-Consent-Manager/commit/475b09e8a5ab461e83757ccf6c2722ba0876e219), and will continue to manually hide dialogs on publisher sites via cookies/css.
