### ISSUE TITLE
Mocha and geckodriver dependency error

### ISSUE THREAD

**Issue by Nebrethar** [SociallyCompute/Global-Consent-Manager#27]
**The Issue**

I ran `npm install` and ran the standard test script. I did not have mocha or geckodriver afterward.
This command errored out on the first couple tries (until i figured out what I needed)

**Computer Specifications**

Widnows 10.0.17134 Build 17134Microsoft Surface Book

**Extra Information**

None

_This issue was submitted via the Global Consent Manager Web Extension_

**Comment by zombie** [comment]
Can you give more details on how to reproduce this, since I can't locally (Windows as well).  Did you try cloning the master into a new dir and installing there?

**Comment by Nebrethar** [comment]
This may have been an isolated incident. I will try on a fresh machine soon and get back with the results.

**Comment by Nebrethar** [comment]
Could not recreate the issue.
