### ISSUE TITLE
CI Unreliable Results.

### ISSUE THREAD

**Issue by Nebrethar** [SociallyCompute/Global-Consent-Manager#28]
**The Issue**

I am having a problem that Travis CI is exceeding the maximum time available to test with mocha.

**Computer Specifications**

Widnows 10.0.17134 
Build 17134
Microsoft Surface Book

**Extra Information**

```Error: Timeout of 90000ms exceeded. For async tests and hooks, ensure "done()" is called```

**Comment by zombie** [comment]
Some unreliability is to be expected (Travis is a free service, and our tests are depending on live sites from 3rd parties).  Some of that can be worked around, but I don't think timeouts is one of those.

Also, you should be able to restart a test run if/when you suspect flakiness.
