### ISSUE TITLE
Not listed yet: www.software.ac.uk

### ISSUE THREAD

**Issue by GeorgLink** [SociallyCompute/Global-Consent-Manager#40]
The website at this url is unlisted: https://www.software.ac.uk/blog/2018-11-12-open-community-metrics-and-privacy-mozfest18-recap

**Comment by Nebrethar** [comment]
This site is now listed in the latest version of Global Consent Manager. Thank you for the issue and let us know if you have any more issues.

**Comment by Nebrethar** [comment]
Also, note that the Mozilla Add-On release will only be updated when I've finished all of the current listing issues. Today or tomorrow.
