### ISSUE TITLE
Not listed yet: www.insights.com

### ISSUE THREAD

**Issue by GeorgLink** [SociallyCompute/Global-Consent-Manager#41]
The website at this url is unlisted: https://www.insights.com/us/resources/a-case-for-leadership-diversity/

**Comment by Nebrethar** [comment]
This site is now listed in the latest version of Global Consent Manager. Thank you for the notification and let us know if you have any more issues.

**Comment by Nebrethar** [comment]
Also, note that the Mozilla Add-On release will only be updated when I've finished all of the current listing issues. Today or tomorrow.
