### ISSUE TITLE
Not listed yet: mybrowseraddon.com

### ISSUE THREAD

**Issue by ryanmk54** [SociallyCompute/Global-Consent-Manager#43]
The website at this url is unlisted: https://mybrowseraddon.com/undo.html?version=0.1.6

**Comment by Nebrethar** [comment]
This site is now listed in the latest version of Global Consent Manager. Thank you for the notification and let us know if you have any more issues.

**Comment by Nebrethar** [comment]
Also, note that the Mozilla Add-On release will only be updated when I've finished all of the current listing issues. Today or tomorrow.
