### ISSUE TITLE
Not listed yet: link.springer.com

### ISSUE THREAD

**Issue by dmarti** [SociallyCompute/Global-Consent-Manager#45]
The website at this url is unlisted: https://link.springer.com/article/10.1365/s40702-018-00474-6

**Comment by Nebrethar** [comment]
This site is now listed in the latest version of Global Consent Manager. Thank you for the notification and let us know if you have any more issues.

**Comment by Nebrethar** [comment]
Also, note that the Mozilla Add-On release will only be updated when I've finished all of the current listing issues. Today or tomorrow.
