### ISSUE TITLE
Not listed yet: www.gallup.com

### ISSUE THREAD

**Issue by GeorgLink** [SociallyCompute/Global-Consent-Manager#46]
The website at this url is unlisted: https://www.gallup.com/

**Comment by Nebrethar** [comment]
This site is now listed in the latest version of Global Consent Manager. Thank you for the notification and let us know if you have any more issues.

**Comment by Nebrethar** [comment]
Also, note that the Mozilla Add-On release will only be updated when I've finished all of the current listing issues. Today or tomorrow.
