### ISSUE TITLE
Not listed yet: www.theneweuropean.co.uk

### ISSUE THREAD

**Issue by kronoc** [SociallyCompute/Global-Consent-Manager#51]
The website at this url is unlisted: https://www.theneweuropean.co.uk/top-stories/wetherspoons-news-magazine-is-being-sent-through-the-post-1-5861134

**Comment by Nebrethar** [comment]
This site is now listed in the latest version of Global Consent Manager. Thank you for the notification and let us know if you have any more issues.

**Comment by Nebrethar** [comment]
Also, note that the Mozilla Add-On release will only be updated when I've finished all of the current listing issues. Today or tomorrow.
