### ISSUE TITLE
Not listed yet: www.brussels-city-shuttle.com

### ISSUE THREAD

**Issue by andreicristianpetcu** [SociallyCompute/Global-Consent-Manager#60]
The website at this url is unlisted: https://www.brussels-city-shuttle.com/en/
![screenshot from 2019-02-03 20-55-38](https://user-images.githubusercontent.com/922368/52181778-176d7c00-27f6-11e9-9188-80b73bf826cb.png)

**Comment by Nebrethar** [comment]
This website is now in the support list and will be in the next release of the GCM web extension on addons.mozilla.org
Thanks!
