### ISSUE TITLE
Documentation on how to add an unlisted site would be useful

### ISSUE THREAD

**Issue by Anntoin** [SociallyCompute/Global-Consent-Manager#66]
I'm sure a lot of people would be willing to contribute rather than just cutting 'Not listed yet' issues.

A guide in the readme with how you'd like contributions submitted would be great.

(It looks like you just need to add some details here https://github.com/SociallyCompute/Global-Consent-Manager/blob/master/src/sites.js but didn't look any further than that)

**Comment by Nebrethar** [comment]
This is a valid point, and your assumption is correct.

The guide is now in the readme under [Adding a Supported Site](https://github.com/SociallyCompute/Global-Consent-Manager#adding-a-supported-site)

Thanks for the feedback!
