### ISSUE TITLE
Not listed yet: www.livemint.com

### ISSUE THREAD

**Issue by andreicristianpetcu** [SociallyCompute/Global-Consent-Manager#97]
The website at this url is unlisted: https://www.livemint.com/Companies/yBajkAZY1Yj0Ia8IYbLXyM/Volkswagen-used-a-derivative-of-its-defeat-device-in-India.html

**Comment by Nebrethar** [comment]
Thank you for the notification. This site is now added to the repository and will be in the next release on addons.mozilla.org.
